before_install:
  - git submodule update --init --recursive


before_script:
  - sh -e /etc/init.d/xvfb start

language: python
python:
  - 2.7

script: py.test --baseurl=https://crash-stats.allizom.org --driver=firefox --destructive


env:
  - DISPLAY=':99.0'


notifications:
  email:
    - webqa-ci@mozilla.org
